spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    changelog: classpath:db/changelog/main_changelog.yaml
  security:
    jwt:
      token-ttl: 86400
      cookie-token-key: ${COOKIE_TOKEN_KEY}
  kafka:
    producer:
      acks: -1
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: pastes

aws:
  region: ru-central1
  endpoint: https://storage.yandexcloud.net
  bucket-name: pastes3
logging:
  level:
    org:
      springframework:
        security: DEBUG